### ISSUE TITLE
This library should have type annotations

### ISSUE THREAD

**Issue by benbariteau** [dnephin/PyStaticConfiguration#108]

**Comment by ymilki** [comment]
@dnephin I'd like to add type annotations to this package.

In the process, would it be reasonable to drop python 2.6 and <3.6 support since these are EOL and add python 3.7, 3.8 support? It would be nice to use the type annotations and avoid the type syntax for older pythons.

**Comment by dnephin** [comment]
Ya, I think dropping EOL'ed versions makes sense. Thanks for working on this!

**Comment by ymilki** [comment]
@dnephin Awesome. Another question, does the travis build work for this repo or would you like to move/add github actions? The pypi/coverage flows need additional configuration, but I can add the flow for build and testing.

**Comment by dnephin** [comment]
It's been a while, so there's a decent chance the travis builds don't work anymore. A new workflow using github actions would be great. Thank you!
