### ISSUE TITLE
Support for yaml binary type

### ISSUE THREAD

**Issue by SBoudrias** [dnephin/PyStaticConfiguration#74]
I couldn't find any support for binary type in yaml file. Does it exist already? Is there plan to add support?

```yaml
key: !!binary some-raw-binary
```

**Comment by dnephin** [comment]
The default `get()`, `read()` will return a value directly without modifying it https://github.com/dnephin/PyStaticConfiguration/blob/master/staticconf/validation.py#L152

So using other types should work

**Comment by SBoudrias** [comment]
Thanks!
