### ISSUE TITLE
staticconf doesn't corrcetly handle yaml files with periods in names

### ISSUE THREAD

**Issue by and471** [dnephin/PyStaticConfiguration#88]
Consider the following file, config.yaml:

```
foo.bar.blah:
  this: true
```

If you run:

```
staticconf.YamlConfiguration(config.yaml', namespace='ns1')
dictionary = staticconf.config.get_namespace(name="ns1").get_config_dict()
```

Then dictionary equals 
```
{
  'foo': {
    'bar': {
      'blah': {
        'this': True
      }
    }
  }
}
```

Instead of 
```
{
  'foo.bar.blah' : {
    'this': True
  }
}
```

**Comment by and471** [comment]
I believe this is because staticconf uses periods to internally represent nesting (https://github.com/dnephin/PyStaticConfiguration/blob/master/staticconf/config.py#L120), and hence can't distinguish between those used for internal representation, and those used in yaml files.

**Comment by and471** [comment]
Possible a better delimeter would be ':', as this can't be used in names in yaml?

**Comment by dnephin** [comment]
`:` can be used in keys, the key just needs to be quoted.

**Comment by and471** [comment]
ah :D well something other than a period then :)

**Comment by dnephin** [comment]
You can use `flatten=False` if you don't want to flatten things: https://pythonhosted.org/PyStaticConfiguration/overview.html#reading-dicts

I don't see any way to change this. I think `.` is an expected delimiter for nested configuration.

**Comment by and471** [comment]
flatten=True or False doesn't affect this. The yaml is being deepen'd (for lack of a better word)

I'm not sure of the way to fix it, but this method is not returning the correct representation of the original yaml

**Comment by jorgeblanco** [comment]
*Note: I think the expected behavior is different (mind the nesting in the second dict)

 Then dictionary equals

```
{
  'foo': {
    'bar': {
      'blah': {
        'this': True
      }
    }
  }
}
```
Instead of
```
{
  'foo.bar.blah' : {
    'this': True
  }
}
```

**Comment by and471** [comment]
yup my bad, updating

**Comment by dnephin** [comment]
I don't think I understand the problem. `staticconf.read('foo.bar.blah.this')` should return the value you want, right?

`get_config_dict()` is more for debugging. All the examples should show using getters or readers to retrieve values.

**Comment by jorgeblanco** [comment]
Is there a getter to get all the top level keys in a file?

**Comment by dnephin** [comment]
There isn't. The keys aren't values

**Comment by jorgeblanco** [comment]
I meant it as a way to get the whole config as a single dict. Getting the keys wasn't the point but getting the key value pairs in a single object

**Comment by and471** [comment]
Hmm seems a good workaround is to use flatten=False, and the use get_config_values(), so we'll use that :)
