### ISSUE TITLE
Upload wheels to pypi?

### ISSUE THREAD

**Issue by asottile** [dnephin/PyStaticConfiguration#94]
This will *slightly* improve installation time in the uncached case (wheel installation is just unzip + pyc compile) vs running setup.py on installation.

`pip wheel . --dest dist && twine upload dist/* --skip-existing` should be sufficient

**Comment by dnephin** [comment]
Would you mind opening a PR for this? The release task is in `dobi.yaml` `job=release`. Right now it just called python directly, but it could also do

```yaml
command: bash -c '
   ...
'
```

or a new script called from here would be fine too. 

Otherwise I can make the change on the next release.

**Comment by asottile** [comment]
I'll add a patch that I think should work :)
