### ISSUE TITLE
License Definition in setup.py?

### ISSUE THREAD

**Issue by JamesElstone** [dnephin/PyStaticConfiguration#97]
Would it be possible to make reference to the License in setup.py please?

Something like:
`LICENSE       = 'APACHE20'`

Would it also be possible to add the LICENSE file to the source distribution (sdist) please?

As background and cross-reference - PyStaticConfiguration is potentially being added to the FreeBSD Ports tree and this request was raised as part of the review cycle. 

The downstream reference is
[https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216204](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216204)

The package being entered into the FreeBSD Ports tree is sourced from
[https://files.pythonhosted.org/packages/source/P/PyStaticConfiguration/](https://files.pythonhosted.org/packages/source/P/PyStaticConfiguration/)

**Comment by dnephin** [comment]
I opened #98 to make those changes.

The `setup.py` does include `License :: OSI Approved :: Apache Software License` in the classifiers. If I'm reading https://docs.python.org/3.6/distutils/setupscript.html#additional-meta-data correctly I think that's correct, but I don't mind adding the other `license` kwarg as well.
